### ISSUE TITLE
Feature Request: Add Known Hosts Documentation

### ISSUE THREAD

**Issue by conradfuhrman** [roots/setup-trellis-cli#4]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

For the sage theme example, additional documentation for the Known Hosts secret should be added.

### Motivation

Reference.

### Additional Context

From the previous action that was archived, here is what was provided:

ssh-known-hosts
Required Known hosts for SSH. Use a [GitHub secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) for this value (example in usageo above).

Since the GitHub Action runner will be the client SSHing into your remote Trellis server, this is needed to allow a connection from GitHub -> your server, which means the known host is for the remote server hostname.

This value is not just the hostname/IP, it needs be in the format that ssh-keyscan returns (OpenSSH format):

ssh-keyscan -t ed25519 -H MY_SERVER_HOSTNAME
Which returns something like this:

|1|nLf9avvc+tz8nFgUW/3tPwjTA4Q=|dLZn1guXUrBjLg4s23ird724guA= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
Note: using trellis key generate will set this secret value automatically.

This value can also be found in your local ~/.ssh/known_hosts file if you've previously connected to the host.

**Comment by swalkinshaw** [comment]
Sorry didn't see this until. Added a section with details.
