### ISSUE TITLE
set a default timeout

### ISSUE THREAD

**Issue by chrillep** [roots/setup-trellis-cli#72]
### Summary

i would argue setting a timeout is a good idea.

docs for jobs and job steps

[jobs.<job_id>.steps[*].timeout-minutes](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes)
The maximum number of minutes to run the step before killing the process.

[jobs.<job_id>.timeout-minutes](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)
The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360

**Comment by swalkinshaw** [comment]
Agreed, timeouts are always smart to have. Did you want to work on this?
