### ISSUE TITLE
💡 Example code of running trellis-cli to setup integration test

### ISSUE THREAD

**Issue by chrillep** [roots/setup-trellis-cli#75]
### Summary

getting a dev environment working inside an action.

### Additional context

might work with `trellis vm` ?

**Comment by retlehs** [comment]
Please use complete sentences to elaborate on your request. This is far too vague. We need more information. What specific problem are you trying to solve?

The Trellis repo contains a GitHub action workflow for an integration test that uses this action.

**Comment by chrillep** [comment]
> Please use complete sentences to elaborate on your request. This is far too vague. We need more information. What specific problem are you trying to solve?
> 
> The Trellis repo contains a GitHub action workflow for an integration test that uses this action.

yes ill be more specific ❤️ .
Just needed to write something down that i could iterate on.

you mean this workflow https://github.com/roots/trellis/blob/fd56f62d0725423d233f97a794a57f6a0755ca30/.github/workflows/integration.yml

**Comment by chrillep** [comment]
Id like to be able to run integration tests against code changes in PR's.

**Comment by swalkinshaw** [comment]
You can copy Trellis' implementation: https://github.com/roots/trellis/blob/master/.github/workflows/integration.yml

It's a bit messy because it provisions directly on the base OS image in actions. I'm sure there's many other ways to start with a better base VM. If you end up trying anything, please let us know how it went.

`trellis vm` requires macOS right now so it wouldn't work.

**Comment by chrillep** [comment]
> `trellis vm` requires macOS right now so it wouldn't work.

good to know !

Yeah once ive pinned something down ill post it.

**Comment by chrillep** [comment]
you can use macos runners. not sure of the caveats there tho.

* https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
* https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
