### ISSUE TITLE
Node16 is deprecated

### ISSUE THREAD

**Issue by aymanrady** [roots/setup-trellis-cli#92]
### Version

1

### What did you expect to happen?

No warnings

### What actually happens?

```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: webfactory/ssh-agent@v0.8.0, roots/setup-trellis-cli@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

Github has [deprecated](https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/) Node16 since June, 30th 2024. webfactory/ssh-agent released `0.9.0` to address this issue.

### Steps to reproduce

```yml
- uses: roots/setup-trellis-cli@v1
```

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Thanks for the issue! Got things updated and just pushed a new release
